#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cd api &&
pipenv run pylint $(git ls-files '*.py') &&
pipenv run pyright $(git ls-files '*.py') &&
pipenv run python -m unittest discover tests &&
cd ..

cd web &&
npm run test &&
cd ..


