name: Build and deploy Python app to Azure Web App - daedalustest

on:
  push:
    branches:
      - ar-gltf-export
  workflow_dispatch:

    # jobs:
    #   build:
    #     runs-on: ubuntu-latest
    # 
    #     steps:
    #       - uses: actions/checkout@v2
    # 
    #       - name: Set up Python version
    #         uses: actions/setup-python@v1
    #         with:
    #           python-version: '3.9'
    # 
    #       - name: Create and start virtual environment
    #         run: |
    #           python -m venv venv
    #           source venv/bin/activate
    #       
    #       - name: Install dependencies
    #         run: pip install -r requirements.txt
    #         
    #       # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
    #       
    #       - name: Upload artifact for deployment jobs
    #         uses: actions/upload-artifact@v2
    #         with:
    #           name: python-app
    #           path: |
    #             . 
    #             !venv/


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Lint and test
        run: |
          cd api
          pip install pipenv
          pipenv install 
          pipenv run pyright $(git ls-files '*.py')
          pipenv run pylint $(git ls-files '*.py')
          pipenv run python -m unittest discover tests
      
      - name: Create and start virtual environment
        run: |
          mv api/* .
          mv api/.env .
          python -m venv venv
          source venv/bin/activate
      - name: Install dependencies from requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Install dependencies frontend
        run: |
          cd web
          npm install
      - name: Run the frontend tests
        run: |
          cd web
          npm test
      - name: Build
        run: |
          cd web
          npm run build
          
      - name: Nuke node_modules
        run: |
          cd web
          rm -rf node_modules
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'daedalustest'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_909628ECF82D4DD390C9F7FF9B0AF3AA }}
